// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace OracleConnectionApp.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class CreateEmployeeAndDepartmentTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateEmployeeAndDepartmentTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201905060601307_CreateEmployeeAndDepartmentTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
